### ISSUE TITLE
Question regarding "entry_*.c": App with Console and GUI modes

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [thpatch/win32_utf8#6]
If I'm trying to make a program that can execute both in console and in a GUI, like if I use a command-line argument in the shortcut "-console" that launches a console alongside the GUI version, or "-nogui" which disables the GUI _and_ automatically launches the console, which entry file am I supposed to use?

**Comment by brliron** [comment]
When you make a program like that, you usually start without a console, then create one with AllocConsole. Because you start without a console, you will use entry_winmain.c .

**Comment by 32th-System** [comment]
And if you want to use things like printf you also need to do 
```c
freopen("CONIN$", "r", stdin); 
freopen("CONOUT$", "w", stdout); 
freopen("CONOUT$", "w", stderr); 
```
